#+options: toc:nil

* Akamai Delivery Property Onboard with Terraform

** Introduction
Akamai security and delivery onboard or handling code with terraform.

This code create a vanilla delivery config, certificate and edgehostname to onboar a brand new configuration
and it adds the hostname to a defined already existent security configuration.

** Path Structure
#+begin_example
.                           -> Delivery onboard code
├── delivery_rules          -> Property manager logic rules 
└── modules
    ├── appsec              -> Akamai Security configuration update
    ├── dns                 -> Akamai EdgeDNS
    ├── enrollment          -> Akamai CPS DV certificate 
    ├── property            -> Akamai Property manager
    └── validation          -> Akamai CPS certificate validation
#+end_example

** Use
1. Setup you Akamai API credentials
2. Create terraform.tfvars file (example.tfvars as reference)
3. Run: terraform Init
4. Import security configuration to tfstate with below code:
   #+begin_src bash
   terraform import module.appsec.akamai_appsec_configuration.config <your appsec configuration>
   #+end_src

5. Run: terraform Plan
6. Run: terraform Apply

** Code Execution WorkFlow
1. Create cpcode named equal to property name (sanitized).
2. Create enrollment for DV certificate.
3. Create edgehostnames enhanced-tls.
4. Create delivery property.
5. Push delivery property to Akamai staging and/or production (based on variables)
6. Update security configuration
7. Push security configuration to Akamai staging and/or production (based on variables)

** Import (if resources exists)
- Enrollment (Certificate)
- Cpcode
- Edgehostnames
- Delivery Property
- Security configuration

** Rererences
1. [[https://github.com/akamai/terraform-examples][GitHub Akamai Terraform Examples]]
2. [[https://terraform.aka-dev.net/][Terraform Training Github]]
3. [[https://techdocs.akamai.com/terraform/][Akamai Terraform Documentation - TechDocs]]
